name: plugin version prediction

on:
  workflow_dispatch:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        path: 'main'
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
          flutter-version: '3.3.10'
          
    - name: 'master version predict'
      run: |
        cd main
        flutter pub get
        ls -l
        flutter pub run pub_version_plus:main patch
        _pluginVersion=$(sed -n '3p' pubspec.yaml)
        set -e
        echo "PLUGIN_VERSION=${_pluginVersion}" >> $GITHUB_ENV
        echo "new version : ${_pluginVersion}"
      
    - uses: actions/checkout@v3
      with:
        path: 'branch'
    - name: 'Update version'
      run: |
        cd branch
        ls branch
        sed -i '' "3 s/.*/${{ env.PLUGIN_VERSION }}/" pubspec.yaml
        cat pubspec.yaml
        git status
        
    - name: 'status'
      run: |
        echo "${{ env.PLUGIN_VERSION }}"
      
