name: plugin version prediction

on:
  workflow_dispatch:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        path: 'main'
    - name: 'status'
      run: ls -l
