name: plugin version prediction

on:
  workflow_dispatch:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        path: 'main'
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
          flutter-version: '3.3.10'
          
    - name: 'master version predict'
      run: |
        cd main
        flutter pub get
        ls -l
        flutter pub run pub_version_plus:main patch
        set -e
        brew install yq
        _pluginVersion=$( yq read pubspec.yaml version )
        echo "PLUGIN_VERSION=${_pluginVersion}" >> $GITHUB_ENV
        echo "new version : ${_pluginVersion}"
    - name: 'status'
      run: |
        env
      
