name: Publish Map JS SDK - Flutter

on:
  push:
    branches:
      - "main"
#     paths:
#       - pubspec.yaml
jobs:
  package_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Capture plugin version
        run: |
          _prefix="version: "
          _pluginVersionText=$(sed -n '3p' < pubspec.yaml)
          _pluginVersion=${_pluginVersionText#"$_prefix"}
          echo "PLUGIN_VERSION=${_pluginVersion}" >> $GITHUB_ENV
          echo "new version : ${_pluginVersion}"
          
      - name: Update change log
        run: |
          echo "## ${{ env.PLUGIN_VERSION }}" >> CHANGELOG.md
          cat whatsnew.md >> CHANGELOG.md
          cat CHANGELOG.md
          
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
          
      - name: Install dependencies
        run: flutter pub get
        
#       - name: Run tests
#         run: flutter pub run test
        
      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./deployment/pubdev.sh
          
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
        
      - name: Publish Package
        run: flutter pub publish -f
          
      
    
      
