name: Publish Map JS SDK - Flutter

on:
  push:
    branches:
      - "main"
jobs:
  package_publish:
  runs-on: ubuntu-latest
  steps:
    - name: Check out Git repository
        uses: actions/checkout@v2
    
      
