name: Publish Map JS SDK - Flutter

on:
  push:
    branches:
      - "main"
    paths:
      - pubspec.yaml
jobs:
  package_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Capture plugin version
        run: |
          _prefix="version: "
          _pluginVersionText=$(sed -n '3p' < pubspec.yaml)
          _pluginVersion=${_pluginVersionText#"$_prefix"}
          echo "PLUGIN_VERSION=${_pluginVersion}" >> $GITHUB_ENV
          echo "new version : ${_pluginVersion}"
          
      - name: Update change log
        run: |
          echo "## ${{ env.PLUGIN_VERSION }}" >> CHANGELOG.md
          cat whatsnew.md >> CHANGELOG.md
          cat CHANGELOG.md
          
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
          
      - name: Install dependencies
        run: flutter pub get
          
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
        
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          accessToken: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Updated CHANGELOG.md"
          commit_prefix: "[AUTO]"
          force: false
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.PLUGIN_VERSION }}
          name: Release ${{ env.PLUGIN_VERSION }}
        

          
      
    
      
